Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "cozycloud-dev-0.1.0"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://www.cozycloud.cc/media/cozycloud-dev-0.1.0.box"

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :hostonly, "192.168.33.10"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  #
  # You can access those on http://localhost:port
  # (instead of http://'config.vm.network':port)
  config.vm.forward_port 9101, 9101 # Cozy Data System
  config.vm.forward_port 9104, 9104 # Cozy Home
  config.vm.forward_port 5984, 5984 # CouchDB
  config.vm.forward_port 6379, 6379 # Redis

  # Execute the initialization script. More details in the script itself.
  # The script must be in local system (default: the shared directory)
  Vagrant::Config.run do |config|
    config.vm.provision :shell, :path => "init-cozycloud.sh"
  end

end
